### ISSUE TITLE
sudo firecfg : Add profiles in ~/.config/firejail

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#1559]
The new profile build tool is very useful - thanks a lot, @netblue30 ! Now that creating one's own profiles is easier than ever - isnt't this an additional argument that `sudo firecfg` should also take the profiles in ~/.config/firejail into account?

**Comment by netblue30** [comment]
Definitely a bug, thanks!

**Comment by netblue30** [comment]
Fixed, you can try it out.

**Comment by curiosity-seeker** [comment]
Thanks, but unfortunately this doesn't seem to work. I tested the profile build tool and created for fun a profile for speedcrunch in ~/.config/firejail. And it's, indeed, used whenever I execute `firejail speedcrunch`:

```
$? ✓ xxx@FEDORA ~ $ firejail speedcrunch
Reading profile /home/xxx/.config/firejail/speedcrunch.profile
```

 However, `sudo firecfg` does **not** add an corresponding symlink in /usr/local/bin.

**Comment by SpotComms** [comment]
It seems to be looking in ~/.configure not ~/.config, see https://github.com/netblue30/firejail/commit/4560185cfe17aff45659bdae51794732e456a433#diff-23090d1a48862a575a2500a2ac321ed4R351

However even then changing that it still doesn't seem to work.

**Comment by netblue30** [comment]
I was looking in the wrong place in the code! I have a new fix in.

**Comment by curiosity-seeker** [comment]
Great! The new fix worked for me :-) Thank you very much!
