### ISSUE TITLE
Various Issues

### ISSUE THREAD

**Issue by SkewedZeppelin** [netblue30/firejail#1755]
Below is a comment by @bmeh copied from [here](https://github.com/netblue30/firejail/issues/1740#issuecomment-361060829)
-------

I would like to note that Electron apps (too) (Wire, for example, amongst many others) have not been working for me for a few months now. I am getting `error while loading shared libraries: libnode.so: cannot open shared object file: No such file or directory`, which could be a problem caused by not having the directory containing the executable and `libnode.so` whitelisted, except it is. At least with a previous version I could just `cd` to the directory that contains `libnode.so` and it would work, but it doesn't work anymore that way either. Additionally, even in this case, the application wouldn't always show up properly (meaning it freezes, not getting displayed as expected), it would just start giving me such errors:

```
[154:0109/161459.161525:ERROR:gles2_cmd_decoder.cc(17403)] [.DisplayCompositor-0x1b3cb0f68000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[154:0109/161459.161653:ERROR:gles2_cmd_decoder.cc(9636)] [.DisplayCompositor-0x1b3cb0f68000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[154:0109/161459.161807:ERROR:gles2_cmd_decoder.cc(17403)] [.DisplayCompositor-0x1b3cb0f68000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[154:0109/161459.161940:ERROR:gles2_cmd_decoder.cc(9636)] [.DisplayCompositor-0x1b3cb0f68000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[154:0109/161459.162080:ERROR:gles2_cmd_decoder.cc(17403)] [.DisplayCompositor-0x1b3cb0f68000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[154:0109/161459.162209:ERROR:gles2_cmd_decoder.cc(9636)] [.DisplayCompositor-0x1b3cb0f68000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[154:0109/161459.162347:ERROR:gles2_cmd_decoder.cc(17403)] [.DisplayCompositor-0x1b3cb0f68000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[154:0109/161459.162476:ERROR:gles2_cmd_decoder.cc(9636)] [.DisplayCompositor-0x1b3cb0f68000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[154:0109/161459.162617:ERROR:gles2_cmd_decoder.cc(17403)] [.DisplayCompositor-0x1b3cb0f68000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[154:0109/161459.162765:ERROR:gles2_cmd_decoder.cc(9636)] [.DisplayCompositor-0x1b3cb0f68000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[154:0109/161459.162917:ERROR:gles2_cmd_decoder.cc(17403)] [.DisplayCompositor-0x1b3cb0f68000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[154:0109/161459.163052:ERROR:gles2_cmd_decoder.cc(9636)] [.DisplayCompositor-0x1b3cb0f68000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
```
And on occasions, it would work as expected (???), but it's pretty rare.

Aaaaand `steam-native` is broken as well. It has been for a while.

Note: all the applications not working with firejail do work without it.

I don't know what changed, but it seems like firejail has been broken for a few months now. I tried downgrading to an older version, but it doesn't work either. Any pointers to a workaround or something? Mind you, `firejail --noprofile foobar` works, but yeah.

Distro: Arch Linux

```
firejail version 0.9.52

Compile time support:
        - AppArmor support is disabled
        - AppImage support is enabled
        - bind support is enabled
        - chroot support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - git install support is disabled
        - networking support is enabled
        - overlayfs support is enabled
        - private-home support is enabled
        - seccomp-bpf support is enabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled
```

`firejail --quiet --private-dev --nodvd --notv ls -1 /dev`:
```
dri
full
log
null
nvidia0
nvidiactl
nvidia-modeset
ptmx
pts
random
shm
snd
tty
urandom
video0
zero
```

Update:

This is very odd, commenting `noroot` in `/etc/firejail/steam.profile` (and `wire.profile`) solves all the issues, and the window is responsive and is displayed correctly. Huh?

**Comment by SpotComms** [comment]
@bmeh `noroot` is known to cause issues with the NVIDIA proprietary drivers. You can run the following command to disable it in all profiles.
`sudo sh -c "echo 'ignore noroot' >> /etc/firejail/globals.local"`

**Comment by chiraag-nataraj** [comment]
fwiw, `noroot` also breaks Electron apps iirc, for reasons that aren't clear.

**Comment by smitsohu** [comment]
@bmeh Can you confirm this is still an issue with Firejail 0.9.54?

**Comment by smitsohu** [comment]
@bmeh Should be fixed in latest Firejail, see also related #1748. Closing the issue, feel free to reopen if you encounter the problem again. Thanks for the report!

**Comment by bmeh** [comment]
@smitsohu Oh my mistake, I did not notice the mention. I am currently holding back version 0.9.54 for a reason I have forgotten, things work well with 0.9.52 + `noroot`. When I get the time, and it will be available in the official packages for Arch Linux, I will upgrade to 0.9.56 and open a new issue if I still have issues like I did with 0.9.54 which is - if I remember correctly - not related to `noroot`. It could have been fixed by now, so who knows. :)

**Comment by bmeh** [comment]
@smitsohu Oh my mistake, I did not notice the mention. I am currently holding back version 0.9.54 for a reason I have forgotten, things work well with 0.9.52 without `noroot`. When I get the time, and it will be available in the official packages for Arch Linux, I will upgrade to 0.9.56 and open a new issue if I still have issues like I did with 0.9.54 which is - if I remember correctly - not related to `noroot`. It could have been fixed by now, so who knows. :)
