### ISSUE TITLE
transmission-qt theme is strange with firejail

### ISSUE THREAD

**Issue by idnovic** [netblue30/firejail#1788]
If I open Transmission-QT the theme is strange.
If I run /usr/bin/transmission-qt everything is fine.

I believe their is an error saving or loading settings too.
I dunno how to insert an image here.
Here is an screenshot [screenshot](https://imagebin.ca/v/3t5H7E0v0x31)

**Comment by SkewedZeppelin** [comment]
This might be related to #1736, an issue that has been fixed in the latest master.

**Comment by idnovic** [comment]
can you point me to source code changes?
I did like to edit my configs until the update

**Comment by SkewedZeppelin** [comment]
Here were all of the related changes https://github.com/netblue30/firejail/issues/1736#issuecomment-358966444

5cf5ec263660009e86f70b8c6aca156011f7541a is probably the only relevant one, I think the other commits were reverting stuff only added after 0.9.52

**Comment by idnovic** [comment]
thank you.

But my issue is not fixed. The thema is still strange.
left is normally opened and right is with firejail
[screenshot](https://imagebin.ca/v/3t5H7E0v0x31)

**Comment by smitsohu** [comment]
Does it maybe work with this one 11a610cbe3470d2176c57d1fdb9cbb0873069bd4 ?

**Comment by idnovic** [comment]
yes it does!
As I saw kvantum I knew it would work.
I did not thought about the theme engine
