### ISSUE TITLE
LibreOffice won't start on Parrot 4.3

### ISSUE THREAD

**Issue by Max1mCom** [netblue30/firejail#2214]
Hi,

I have faced with issue on Parrot 4.3:

```
$libreoffice %U
Reading profile /etc/firejail/libreoffice.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 18644, child pid 18645
Child process initialized in 84.41 ms
Final linking of kernel DynamicKernel failed.

Parent is shutting down, bye...
```
```
$firejail --apparmor libreoffice
Reading profile /etc/firejail/libreoffice.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 18747, child pid 18748
Child process initialized in 88.34 ms
Warning: an existing sandbox was detected. /usr/bin/libreoffice will run without any additional sandboxing features
Final linking of kernel DynamicKernel failed.

Parent is shutting down, bye...
```

**Comment by smitsohu** [comment]
Can you please do the following?

If `firejail --noprofile libreoffice` works, run `firejail --tracelog libreoffice`
If it doesn't work, run `firejail --noprofile --tracelog libreoffice`

and check `journalctl | grep blacklist` if there is something related to libreoffice.

Thanks.

**Comment by SkewedZeppelin** [comment]
@smitsohu iirc Parrot ships many modified profiles.

@Max1mCom can you also paste in `/etc/firejail/libreoffice.profile` too?

**Comment by Max1mCom** [comment]
Hello guys, thank you for your help.

> Can you please try if `firejail --noprofile libreoffice` works?
> Somethings else to try would be firejail --tracelog libreoffice

These commands are `freezing` my system:
https://prnt.sc/lbn7r6

And command `sudo journalctl | grep blacklist` gives me the blank output. I mean, it doesn't output anything.

**Comment by Max1mCom** [comment]
And LibreOffice doesn't work on Parrot right after installation.
I use ru-RU locale.

**Comment by Max1mCom** [comment]
> can you also paste in `/etc/firejail/libreoffice.profile` too?

```
┌─[✗]─[max@parrot]─[~]
└──╼ $sudo cat /etc/firejail/libreoffice.profile
# Firejail profile for libreoffice
# Description: Office productivity suite
# This file is overwritten after every install/update
# Persistent local customizations
include /etc/firejail/libreoffice.local
# Persistent global definitions
include /etc/firejail/globals.local

noblacklist ${HOME}/.java
noblacklist /usr/local/sbin
noblacklist ${HOME}/.config/libreoffice

# libreoffice uses java; if you don't care about java functionality,
# comment the next four lines
noblacklist ${PATH}/java
noblacklist /usr/lib/java
noblacklist /etc/java
noblacklist /usr/share/java

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-passwdmgr.inc
include /etc/firejail/disable-programs.inc

include /etc/firejail/whitelist-var-common.inc

# Ubuntu 18.04 uses its own apparmor profile
# uncomment the next line if you are not on Ubuntu
apparmor
caps.drop all
machine-id
netfilter
#nodbus
nodvd
nogroups
#nonewprivs - fix for Ubuntu 18.04/Debian 10
noroot
notv
#protocol unix,inet,inet6  - fix for Ubuntu 18.04/Debian 10
#seccomp  - fix for Ubuntu 18.04/Debian 10
shell none
#tracelog - problems reported by Ubuntu 18.04 apparmor profile in /var/log/syslog

private-dev
private-tmp

noexec ${HOME}
noexec /tmp

join-or-start libreoffice
┌─[max@parrot]─[~]
```

**Comment by smitsohu** [comment]
> Final linking of kernel DynamicKernel failed.

Maybe some problem with the DKMS. 
Can you then please try another one?

I you have not done so yet, please run libreoffice  _once without_ firejail. To do this, give the absolute path on the commandline, e.g. /usr/bin/loffice. Afterwards try if you can start it with firejail as normal.

Should this not help, another command would be `firejail --noprofile --allow-debuggers --writable-var --noblacklist=/sys/* libreoffice`. If that one works, it would be awesome if you could juggle a bit with the options to find the minimal required set.

Thanks.

**Comment by Max1mCom** [comment]
Hello,

Thanks a lot.

`$firejail --noprofile --allow-debuggers --writable-var --noblacklist=/sys/* libreoffice` still freezes interface.

But `$/usr/bin/loffice` is working.
And after that `$loffice` is working too.
Libreoffice now is launching as usual.

**Comment by Abdibasidissack** [comment]
can you explain the steps you've taken to solve it

**Comment by Max1mCom** [comment]
Hi,
I don't remember exactly.
Just try to run the following command from my previus message:
`/usr/bin/loffice`

And also try to update your system packages:
`sudo apt update && sudo apt upgrade`

It's quite the old issue, I think it should be fixed.

**Comment by bgagan911** [comment]
/usr/bin/loffice

Works!!!!

**Comment by Abdibasidissack** [comment]
Thank you.
It works.

**Comment by Soheibooo** [comment]
I can confirm the problem is still there in Parrot Security 4.6. `/usr/bin/loffice` did the trick. Thanks! :kissing_smiling_eyes:

**Comment by ContactLeft** [comment]
Has this been fixed? 

Neither one of these workarounds work for me.

**Comment by mjell027** [comment]
As @smitsohu already said this worked for me: 
If you have not done so yet, please run libreoffice once without firejail.
To do this, give the absolute path on the commandline, e.g. /usr/bin/loffice.
