### ISSUE TITLE
bug with private-bin and /usr/local/bin

### ISSUE THREAD

**Issue by nick75e** [netblue30/firejail#553]
Hi!

With previous versions, when I wanted to sandbox gthumb with `private-bin`, I would create a file in `/usr/local/bin/` to make it work system-wide but now with v0.9.40, it doesn't work any more.
It says: `execvp: No such file or directory`
I think it comes from the fact that firejail now also modifies `/usr/local/bin/` whereas it was left untouched before. I can make firefox work because `/usr/bin/firefox` is a symlink, I just have to point to the real file.

**Comment by netblue30** [comment]
Yes, it is a bug. Adding /usr/local/bin to private-bil list is breaking firejail symbolic links in /usr/local/bin. I'll bring in a fix shortly, thank you for the bug.

**Comment by netblue30** [comment]
Fixed!

**Comment by nick75e** [comment]
Thanks for the fast fix.
I tried to compile but the files are not in the same directories as with the .deb file.
How can I make the compiling process work like the .deb file?

**Comment by netblue30** [comment]
Do your git clone, go into firejail directory followed by "./configure --prefix=/usr", then do  a "make deb". When is done, you have a new deb file in firejail directory.

**Comment by nick75e** [comment]
The fix doesn't work, I still get `execvp: No such file or directory`. :-(

**Comment by netblue30** [comment]
Give me some more data. How are you starting it?

**Comment by nick75e** [comment]
here's how to reproduce:
```
sudo echo "firejail /usr/bin/gthumb" > /usr/local/bin/gthumb
sudo chmod +x /usr/local/bin/gthumb
gthumb
```
- up to v0.9.38: OK
- v0.9.40: `execvp: No such file or directory`

Note: `/usr/bin/gthumb` is a binary not a symlink

**Comment by netblue30** [comment]
It looks like I've fixed a different problem! Instead of "firejail /usr/bin/gthumb" put "firejail --debug /usr/bin/gthumb", run it from a terminal and put output here. Also, what do you have in the profile?

**Comment by nick75e** [comment]
Here you are:
[Output](https://gist.github.com/nick75e/5f4db369b93c5e30fa45881c4f18af0d)
[gthumb.profile](https://gist.github.com/nick75e/fc0abad001f332eceefa57670e895a85)
[block.inc](https://gist.github.com/nick75e/1a144ac49488ebcaf58c7f3093694bcb)
[common_bin.inc](https://gist.github.com/nick75e/56daf869038730484c4f7f6fe84746c2)

**Comment by netblue30** [comment]
Make /usr/local/bin/gthumb a symbolic link to /usr/bin/firejail instead of a bash script. --private-bin grabs only the first file in the path, so your script ends up starting itself. 

You need the development version 0.9.41, it has  the original fix for firejail symbolic links. Then, you remove the script and add the symlink instead:
`````
$ sudo rm /usr/local/bin/gthumb 
$ sudo ln -s /usr/bin/firejail /usr/local/bin/gthumb
`````

**Comment by nick75e** [comment]
Yes, it works! Thanks a lot!
_Closing..._
