### ISSUE TITLE
Do not print anything in `--quiet` mode

### ISSUE THREAD

**Issue by vn971** [netblue30/firejail#636]
A minor issue. Firejail should not print anything in `quiet` mode.

`firejail --noprofile --quiet true`

**Comment by netblue30** [comment]
This was already fixed in git. What version are you running?

**Comment by vn971** [comment]
I re-compiled just now. (In ArchLinux via this package: https://aur.archlinux.org/packages/firejail-git/  https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=firejail-git).

The output I get:
```
[16:46:49:vasya@p850a:~] firejail --version
firejail version 0.9.41
[16:46:52:vasya@p850a:~] firejail --noprofile --quiet true

[16:49:05:vasya@p850a:~] 
```

**Comment by netblue30** [comment]
Cool, I'll close it for now. Keep an eye on it, this --quiet thing seems to break from time to time, as I add new features. Thanks!

**Comment by vn971** [comment]
@netblue30 wait, the issue is still here. I compiled `firejail` just now to check https://github.com/netblue30/firejail/issues/498 but `firejail --quiet` still shows the text above (one unnecessary \n).

**Comment by icefox** [comment]
Debian backports using firejail version 0.9.40 has this bug...

**Comment by icefox** [comment]
It is a bit surprising actually as I would expect quiet to be the default mode and --verbose to be the option I turn on to get debug output.

> this --quiet thing seems to break from time to time
 
You want to fix that once and for all.  It is hard to use a wrapper if you can't trust it to not interfere with output.

**Comment by netblue30** [comment]
There have been some changes to quiet since 0.9.40. I'll make it easy to run it as a wrapper from a bash script

**Comment by vn971** [comment]
@netblue30 yeah, it still needs fixing. Re-compiled firejail just now to check.

**Comment by netblue30** [comment]
I've just added support to disable all output by default. In a text editor open /etc/firejail/firejail.config and add:
`````
quiet-by-default yes
`````

**Comment by vn971** [comment]
@netblue30 Thanks!
To explain this to others, I observe the new version of firejail supporting both the `--quiet` flag and the configuration option. The behavior itself seems to be fixed.
